### ISSUE TITLE
[OpenAPI] OpenAPI 3.0 support for API generation

### ISSUE THREAD

**Issue by milindaperera** [wso2/integration-studio#271] opened 2020-03-27 17:18 UTC
**Description:**
Add support for OpenAPI 3.0 support for API template generation feature in IntegrationStudio

**Related Issues:**
https://github.com/wso2/product-ei/issues/5018

**Comment by GDLMadushanka** [comment] 2021-03-24 10:12
Fixed in https://github.com/wso2/integration-studio/pull/640

**Closed by GDLMadushanka** 2021-03-24 10:12 UTC
Labels: 8.0.0, Priority/Highest

**Comment by GDLMadushanka** [comment] 2021-03-24 10:13
Duplicate of https://github.com/wso2/integration-studio/issues/618
